### PR TITLE
Clean benches

### PR DESCRIPTION
**Pull request by privat**
Some janitoring in the benchmarks directory

### CODE REVIEW

**Comment by R4PaSs** [comment]
:shipit:

**Comment by Morriar** [comment]
Seeing all that .gitignore updates,

Mmaybe one idea would be to add a test in Jenkins taht checks if the workdir is left dirty (generated but unignored files)

+1 anyway

**Comment by privat** [comment]
If fact, it is :)

It it way I added them

http://gresil.org/jenkins/job/nit_bench/67/testReport/

**Comment by Morriar** [comment]
Excellent

**Pull request merged**
