### PR TITLE
Autoinit abstract attributes

### LINKED ISSUE #1316: A single abstract attribute breaks the autoinit signature
~~~nit
class A
	var w: Bool
	var x: Int is abstract
	var y: Float
end

var a = new A # This should not be accepted, but it is.
~~~

### PR DESCRIPTION
**Pull request by privat**
Fix #1316

### CODE REVIEW

**Comment by xymus** [comment]
+1

**Comment by Morriar** [comment]
+1

**Comment by R4PaSs** [comment]
:shipit:

**Comment by privat** [comment]
reroll: try to pass tests

**Pull request merged**
