### PR TITLE
Kill `model_utils`

### LINKED ISSUE #710: src: cleanup model_utils
Some stuff inside need to be moved to model, some other suff need to die

### PR DESCRIPTION
**Pull request by Morriar**
This PR removes the so hated module `model_utils`:

* Useful services are kept in a new module `model::model_collect` that allows to collect and filter things from a `Model`.
* Clients are migrated from `model_utils` to `model_collect` one by one. Misc functionalities used only by one client are moved in the client.

Fixes #710

### CODE REVIEW

**Comment by privat** [comment]
while I'm happy that `model_utils` is no more, I thing that having query-services on a model as a whole without a `mainmodule` will come back to bite you since any throw-away module or side-things will be collected by client of the libraries.
While this may work in nitdoc because you control what is in the model, this may cause unwanted effects elsewhere.

**Comment by privat** [comment]
+1 anyway

**Comment by Morriar** [comment]
Reroll

* Fixed tests for `nituml`
* @privat, I understand your concern but this kind of features is really usefull for tools that need a global view on the model unlike the compilers. I added a warning in the module comment to clarify that.

**Comment by R4PaSs** [comment]
:shipit:

**Comment by Morriar** [comment]
I don't understand why Jenkins stills say that:
~~~
src/doc/doc_phases/doc_structure.nit:455: new blank line at EOF.
~~~

When there is no more line 455 in [doc_structure.nit](https://github.com/privat/nit/pull/1376/files#diff-d8d28259a7329c2a702fadf66a63b9f3R454)...

**Comment by privat** [comment]
Please solve the merge conflicts.

**Comment by Morriar** [comment]
Reroll to fix merge conflict

**Comment by privat** [comment]
Reroll again to fix merge conflicts :)

**Comment by Morriar** [comment]
Reroll: resolved merge conflicts

**Pull request merged**
