### PR TITLE
location: introduce `from_string` constructor

### PR DESCRIPTION
**Pull request by Morriar**
Useful to build a Location from it's string representation.

Signed-off-by: Alexandre Terrasa <alexandre@moz-code.org>

### CODE REVIEW

**Comment by privat** [comment]
+1 (tests are fine, I just remotely broke the Android install)

**Comment by jpages** [comment]
+1

**Comment by R4PaSs** [comment]
:shipit:

**Comment by xymus** [comment]
:shipit:

**Pull request merged**
