### PR TITLE
Use self in the FFI

### PR DESCRIPTION
**Pull request by xymus**
As requested by everyone, replace the id `recv` by `self` in all Nit FFIs, and their users.

This PR must be integrated before regenerating c_src and using the light FFI in bootstrap critical code.

There is a few commits to update the style of files that caused white space errors.

### CODE REVIEW

**Comment by jpages** [comment]
+1

**Comment by privat** [comment]
+1

**Comment by jpcaissy** [comment]
+1 x :100:

**Comment by Morriar** [comment]
Yeay +1

I already imagine you in the next 2 weeks constantly using `recv` instead of `self` haha.

**Pull request merged**
