### PR TITLE
Portable stack-traces

### LINKED ISSUE #1357: Unable to make NIT without libunwind8-dev
~~~
***************************************************************
* Compile binaries from NIT source files                      *
***************************************************************
./git-gen-version.sh
./nitc_0 --semi-global -v --dir ../bin nitc.nit nitpick.nit nit.nit nitdoc.nit nitls.nit nitunit.nit nitpretty.nit nitmetrics.nit nitx.nit nitlight.nit nitdbg_client.nit nitserial.nit
make[1]: ./nitc_0: Command not found
make[1]: *** [../bin/nitc] Error 127
make[1]: Leaving directory `/home/istvan/nit/src'
make: *** [tools] Error 2
~~~

View with libunwind8

### PR DESCRIPTION
**Pull request by privat**
Most detection of the availability of libunwind and the flags to use is moved at the C compilation time (in the Makefile) instead at the Nit compilation time.

Moreover, if libunwind is not available, then stacktraces are just disabled (instead of aborting).

Another advantage is that the generated C is more portable and can be compiled in a different system.
Thus, this will help cross-compilation and should even enable the bootstrap on libunwind-less system like raspberrypi once c_src is regenerated (cf #1149).

The option `--stacktrace` is also replaced with a simpler `--no-stacktrace` for people that want to disable it completely at C-compile time.

Close #1357 and an item in #864.

### CODE REVIEW

**Comment by R4PaSs** [comment]
:shipit:

**Comment by Morriar** [comment]
+1

**Comment by privat** [comment]
reroll: improved documentation and added an option `--no-stacktrace` for @xymus

**Comment by xymus** [comment]
+1

**Pull request merged**
