### PR TITLE
Option --keep-going

### PR DESCRIPTION
**Pull request by privat**
Follow up of #959 and #1241. Now an option is exposed so people can happily try to use it on various tools that will turn them berserk and make them want to kill you.

### CODE REVIEW

**Comment by privat** [comment]
Kids, do not `./tests.sh -o --keep-going *.nit` at home. I'm a professional and I barely make it out alive.

**Comment by xymus** [comment]
It looks like the much requested `fuckit.nit`, our own version of https://github.com/mattdiamond/fuckitjs 

@ppepos will be happy.

It's surprising that there was already the `keep_going` boolean in place. Was it used only by nitpick?

:shipit: !

**Comment by privat** [comment]
Currently only nitpick and nitls (because broken code need highlighting too). I was tired to manually set the bool to true and recompile the others tools, so I just made an option.

**Comment by BlackMinou** [comment]
+1

**Comment by privat** [comment]
@xymus: @Morriar alreasy mentionned fuckit and @ppepos in #1241

**Pull request merged**
