### PR TITLE
Performance update on Buffer

### PR DESCRIPTION
**Pull request by R4PaSs**
This PR heavily improves the performance on FlatBuffer by introducing cache mechanisms on indexed access.

This is possible through removal of byte-level manipulation on Buffers and re-introduction of a constant-time length attribute on Buffer.

nitmd is now practicable again and should no longer take too much time when running benches.

NOTE: Take only into account the last 2 commits as the 7 first ones are from #1628

### CODE REVIEW

**Comment by Morriar** [comment]
Some benches about the nitmd perfs?

**Comment by R4PaSs** [comment]
Sure, on my machine:

Before:
output

After:
output

There's definitely a slowdown compared to before (by before I mean before UTF-8), but it's certainely way more acceptable now.

**Comment by R4PaSs** [comment]
And for all you number-lovers

# BEFORE

## block_quote
./engines/nitmd/nitmd-o ./benches/out/block_quote.md 200
1. 3.17
2. 3.19
3.17 3.19 3.19 3.19 "block_quote" (./out/nitmd-o.dat)

## code_block
./engines/nitmd/nitmd-o ./benches/out/code_block.md 200
1. 1.56
2. 1.57
1.56 1.57 1.57 1.57 "code_block" (./out/nitmd-o.dat)

## emphasis
./engines/nitmd/nitmd-o ./benches/out/emphasis.md 200
1. 3.76
2. 3.74
3.76 3.74 3.74 3.74 "emphasis" (./out/nitmd-o.dat)

## fast_link
./engines/nitmd/nitmd-o ./benches/out/fast_link.md 200
1. 5.20
2. 5.23
5.20 5.23 5.23 5.23 "fast_link" (./out/nitmd-o.dat)

## full_image
./engines/nitmd/nitmd-o ./benches/out/full_image.md 200
1. 15.06
2. 14.65
15.06 14.65 14.65 14.65 "full_image" (./out/nitmd-o.dat)

## full_link
./engines/nitmd/nitmd-o ./benches/out/full_link.md 200
1. 15.94
2. 15.95
15.94 15.95 15.95 15.95 "full_link" (./out/nitmd-o.dat)

## inline_code
./engines/nitmd/nitmd-o ./benches/out/inline_code.md 200
1. 3.49
2. 3.47
3.49 3.47 3.47 3.47 "inline_code" (./out/nitmd-o.dat)

## inline_html
./engines/nitmd/nitmd-o ./benches/out/inline_html.md 200
1. 11.07
2. 11.49
11.07 11.49 11.49 11.49 "inline_html" (./out/nitmd-o.dat)

## manual_break
./engines/nitmd/nitmd-o ./benches/out/manual_break.md 200
1. 3.20
2. 3.17
3.20 3.17 3.17 3.17 "manual_break" (./out/nitmd-o.dat)

## mixed
./engines/nitmd/nitmd-o ./benches/out/mixed.md 200
1. 12.50
2. 12.50
12.50 12.50 12.50 12.5 "mixed" (./out/nitmd-o.dat)

## ref_link
./engines/nitmd/nitmd-o ./benches/out/ref_link.md 200
1. 10.76
2. 10.83
10.76 10.83 10.83 10.83 "ref_link" (./out/nitmd-o.dat)

## special_xml_chars
./engines/nitmd/nitmd-o ./benches/out/special_xml_chars.md 200
1. 162.58
2. 162.84
162.58 162.84 162.84 162.84 "special_xml_chars" (./out/nitmd-o.dat)

## strong
./engines/nitmd/nitmd-o ./benches/out/strong.md 200
1. 3.71
2. 3.68
3.71 3.68 3.68 3.68 "strong" (./out/nitmd-o.dat)

## unordered_list
./engines/nitmd/nitmd-o ./benches/out/unordered_list.md 200
1. 3.51
2. 3.48
3.51 3.48 3.48 3.48 "unordered_list" (./out/nitmd-o.dat)

# AFTER

## block_quote
./engines/nitmd/nitmd-o ./benches/out/block_quote.md 200
1. 3.22
2. 3.23
3.22 3.23 3.23 3.23 "block_quote" (./out/nitmd-o.dat)

## code_block
./engines/nitmd/nitmd-o ./benches/out/code_block.md 200
1. 1.58
2. 1.57
1.58 1.57 1.57 1.57 "code_block" (./out/nitmd-o.dat)

## emphasis
./engines/nitmd/nitmd-o ./benches/out/emphasis.md 200
1. 3.80
2. 3.86
3.80 3.86 3.86 3.86 "emphasis" (./out/nitmd-o.dat)

## fast_link
./engines/nitmd/nitmd-o ./benches/out/fast_link.md 200
1. 5.38
2. 5.34
5.38 5.34 5.34 5.34 "fast_link" (./out/nitmd-o.dat)

## full_image
./engines/nitmd/nitmd-o ./benches/out/full_image.md 200
1. 14.74
2. 14.88
14.74 14.88 14.88 14.88 "full_image" (./out/nitmd-o.dat)

## full_link
./engines/nitmd/nitmd-o ./benches/out/full_link.md 200
1. 16.64
2. 16.15
16.64 16.15 16.15 16.15 "full_link" (./out/nitmd-o.dat)

## inline_code
./engines/nitmd/nitmd-o ./benches/out/inline_code.md 200
1. 3.50
2. 3.62
3.50 3.62 3.62 3.62 "inline_code" (./out/nitmd-o.dat)

## inline_html
./engines/nitmd/nitmd-o ./benches/out/inline_html.md 200
1. 11.54
2. 12.62
11.54 12.62 12.62 12.62 "inline_html" (./out/nitmd-o.dat)

## manual_break
./engines/nitmd/nitmd-o ./benches/out/manual_break.md 200
1. 3.46
2. 3.37
3.46 3.37 3.37 3.37 "manual_break" (./out/nitmd-o.dat)

## mixed
./engines/nitmd/nitmd-o ./benches/out/mixed.md 200
1. 13.34
2. 13.55
13.34 13.55 13.55 13.55 "mixed" (./out/nitmd-o.dat)

## ref_link
./engines/nitmd/nitmd-o ./benches/out/ref_link.md 200
1. 11.32
2. 11.51
11.32 11.51 11.51 11.51 "ref_link" (./out/nitmd-o.dat)

## special_xml_chars
./engines/nitmd/nitmd-o ./benches/out/special_xml_chars.md 200
1. 166.30
2. 164.30
166.30 164.30 164.30 164.3 "special_xml_chars" (./out/nitmd-o.dat)

## strong
./engines/nitmd/nitmd-o ./benches/out/strong.md 200
1. 3.74
2. 3.78
3.74 3.78 3.78 3.78 "strong" (./out/nitmd-o.dat)

## unordered_list
./engines/nitmd/nitmd-o ./benches/out/unordered_list.md 200
1. 3.57
2. 3.56
3.57 3.56 3.56 3.56 "unordered_list" (./out/nitmd-o.dat)

**Comment by R4PaSs** [comment]
Reroll: tests passing

**Comment by privat** [comment]
before (master) 13.7GIr
after (master+#1628) 14.27GIr
after again  (master+#1628+#1632) 14.3GIr
http://jenkins.gresil.org/jenkins/job/nit_bootstrap/PerfPublisher/

I was told there would be performances :(

**Comment by R4PaSs** [comment]
Less losses certainely, but an improvement of performances at the same time as an improvement in security would be surprising :)

Though the performance loss when merging #1632 kind of surprises me, I know we don't have much FlatBuffers in the compiler, but still, since all the operations are faster than with master, I'd expect it to be slightly faster in global !

I'll check on that

**Comment by R4PaSs** [comment]
Basically, the book keeping is what causes the extra cost in this PR, since all add operations now have an extra `length += 1` statement, this causes a 3 MIr increase in the compiler.

And since no `FlatBuffer[]` or `FlatBuffer[]=` are actually used, there is no real improvement on this side (programs like Markdown however do this a lot and benefit accordingly)

**Comment by privat** [comment]
+1

**Comment by Morriar** [comment]
+1

**Comment by privat** [comment]
Since #1628 was rebased, this one conflicts with it

**Pull request merged**
