### PR TITLE
Regeneration of c_src

### LINKED ISSUE #1426: make: C warning
When compiling nit from sources (origin/master)
~~~sh
$ make
cd src; make
make[1]: Entering directory `/home/morriar/dev/projects/nit/src'
***************************************************************
* Compile nitc_0 from NIT source files                        *
***************************************************************
./git-gen-version.sh
Version v0.7.4-493-gf38919d
../c_src/nitg  -o nitc_0 -v nitc.nit
*** PARSE ***
*** SEMANTIC ANALYSIS ***
*** PROCESS nitc ***
*** GENERATING C ***
*** WRITING C ***
*** COMPILING C ***
standard__string.sep.2.c: In function ‘standard__string___Byte___byte_to_s_len’:
standard__string.sep.2.c:3952:1: warning: passing argument 1 of ‘native_byte_length_str’ makes integer from pointer without a cast [enabled by default]
 var1 = native_byte_length_str(self);
 ^
In file included from standard__string.sep.0.h:212:0,
                 from standard__string.sep.2.c:1:
string_nit.h:18:6: note: expected ‘unsigned char’ but argument is of type ‘struct val *’
 long native_byte_length_str(unsigned char recv);
      ^
standard__string.sep.2.c: In function ‘standard__string___Byte___native_byte_to_s’:
standard__string.sep.2.c:3960:1: warning: passing argument 1 of ‘native_byte_to_s’ makes integer from pointer without a cast [enabled by default]
 native_byte_to_s(self, p0, p1);
 ^
In file included from standard__string.sep.0.h:212:0,
                 from standard__string.sep.2.c:1:
string_nit.h:19:6: note: expected ‘unsigned char’ but argument is of type ‘struct val *’
 void native_byte_to_s(unsigned char recv, char* str, long buflen);
      ^
~~~

### PR DESCRIPTION
**Pull request by privat**
Last one was Fri Feb 6, four months ago.

Close #1426

### CODE REVIEW

**Comment by R4PaSs** [comment]
:shipit:

**Comment by privat** [comment]
I propose to postpone the regeneration c_src until #1499 and #1498 are more investigated (and hopefully solved). If we can regenerate a c_src that have a good behavior on mac this could be more useful

**Comment by privat** [comment]
reroll with fixes for mac. @anis79 confirmed the bootstrap on mac can be done in a reasonable amount of time (3min)

**Comment by jpages** [comment]
+1

**Comment by Morriar** [comment]
+1

**Comment by Tagachi** [comment]
+1

**Comment by jpcaissy** [comment]
:sheep: :it:

**Pull request merged**
