### PR TITLE
nitdoc: use svg instead of png

### PR DESCRIPTION
**Pull request by Morriar**
NItdoc asks `dot` to render svg format instead of png.

Advantages:
* better performances
* less files
* better image quality
* css-able

Benchmarks against nitdoc-next (#1446):
image

### CODE REVIEW

**Comment by privat** [comment]
the `tmp` commit is gross.

Maybe keep the png+map as an alternative that user can select with a flag like `--png-graph`?

**Comment by Morriar** [comment]
Reroll:
* renamed the `tmp` commit
* commented on the 6 first lines skip

I did not add png+map option since I don't think it's really useful unless we have a windows support and compatibility requirements with Internet Explorer < 8.

Also, the [demo is up](http://moz-code.org/demos/nitdoc-svg//stdlib/class_standard__collection__array__Array.html)!

**Comment by R4PaSs** [comment]
:shipit: !

**Comment by privat** [comment]
+1

**Pull request merged**
