### PR TITLE
Opportunity templates and pizzas

### PR DESCRIPTION
**Pull request by xymus**
Adds templates to the Opportunity meetup creation page. The default software provides: 4 kinds of pizzas, 5 days work week and 7 days week. The software customized for xymus.net also provides: pizzas special LATECE and meeting hours for UQAM Sciences.

It is already available at http://xymus.net/opportunity/.

### CODE REVIEW

**Comment by privat** [comment]
+1

I like the detail of the separate local-latece-uqam things from the general templates in the business logic.

**Comment by R4PaSs** [comment]
:shipit: !
But why translate the name of the software to `Opportunité` in French ? Should not the name of the software stay the same, regardless of the language ?

**Comment by privat** [comment]
Loi 101?

Le jeu. 25 juin 2015 10:19, Lucas Bajolet <notifications@github.com> a
écrit :

**Comment by R4PaSs** [comment]
If we go all the way through this path then a well-known OS should change its name to `Fenêtres` in its French distribution, but this would only make it even more ridiculous :)
I do think the name should be uniform for all languages, but I'm not that shocked after all, we can name it `Opportunité`, I don't mind, it just caught my attention

**Comment by privat** [comment]
The pun is still here. So I'm fine. I don't know how it will be in the German, Japanese and Polish.

**Pull request merged**
