### PR TITLE
Apply optional params in strip_extension, basename and join

### PR DESCRIPTION
**Pull request by xymus**
Using optional parameters, the methods `strip_extension`, `basename` and `join` have a default behavior that fit most usage.

* `Collection::join` appends all elements of the collection by default, the same as `join("")`. This is the old behavior of `Collection::to_s`.

* `String::strip_extension` removes the rightmost extension by default, the same as `s.strip_extension("." + s.file_extension)`.

* `String::basename` does not strip the extension by default.

I haven't updated any users of `strip_extension` because the default behavior requires more work. Thus changing the already existing calls to something else would slow down the programs by a very small margin.

### CODE REVIEW

**Comment by R4PaSs** [comment]
Good idea ! :shipit:

**Comment by privat** [comment]
I can live without it but I may prefer that basename let the extension by default (ie defaulting to "").
It is the default behavior of the old shell command `basename`, thus the same behavior in Perl and Ruby . Moreover, the Python's basename never removes the extension (there is no optional argument).

**Comment by xymus** [comment]
@privat It makes sense, I've made the change and updated the PR description.

**Comment by privat** [comment]
+1

**Comment by BlackMinou** [comment]
+1

**Comment by Morriar** [comment]
It bothers me that `a.join == a.join("") == a.join(null)`.

The only thing I hate more than optional parameters is when you use them to code default behavior.

-1 (but there is already 3 +1, so it's useless :p)

**Pull request merged**
