### PR TITLE
Microbenches for niti

### PR DESCRIPTION
**Pull request by privat**
Some update on tests/ so that niti (and nitvm) can pass more tests

### CODE REVIEW

**Comment by jpages** [comment]
+1, I noticed that test_glsl_validation.nit failed in these two engines.

Maybe it could be skipped ?

**Comment by privat** [comment]
test_glsl_validation.nit does not fail, they fixme with notyetimplemented, do you have a different behavior?

**Comment by Morriar** [comment]
+1

**Comment by xymus** [comment]
+1

**Comment by jpages** [comment]
Sorry, I do not have the right configuration, when I execute it I get "test_glsl_validation.nit:31,7--26: Warning: program `glslangValidator` not in PATH, cannot validate this shader."

This is why it failed on my computer(s).

**Comment by BlackMinou** [comment]
+1

**Pull request merged**
