### PR TITLE
Generalize instance creation service so FFI can use it

### LINKED ISSUE #1145: New NativeString in FFI
There seems to be a problem either within FFI or with the way the `new` property of `NativeString` is defined in the Model, such that when using it in FFI, the compiler crashes with a `No provided declaration for NEW_standard__NativeString`.

Since the property is similar, I suspect `NativeArray` to behave similarly.

Here's an example of code that exposes this behaviour.

~~~nit
class A
        fun foo: NativeString import NativeString `{
                return new_NativeString(50);
        `}
end

var x = new A
var ns = x.foo
~~~

### PR DESCRIPTION
**Pull request by xymus**
Move up instance creation from ANew to AbstractCompilerVisitor so they can be used from the FFI implementation. Allows to call extern constructors of extern classes from extern code, and fix #1145.

### CODE REVIEW

**Comment by R4PaSs** [comment]
Nice to see this issue taken care of so quickly !

Once tests are passing, you get my +1 !

**Comment by Morriar** [comment]
+1

**Comment by jpages** [comment]
+1

**Comment by xymus** [comment]
Rerolled to bring back the `return` in case of `NativeArray`.

**Comment by privat** [comment]
Il faudra faire quelque chose pour les `new NativeArray`  mais c'est OK pour l'instant

**Pull request merged**
