### PR TITLE
Rename all REAMDE to README.md

### LINKED ISSUE #1382: The main README file is not in markdown?
I don't know if there is a reason for it, but why is the main README file not in markdown? Since this is the first documentation we see when coming to the repository, the rendering by Github would look better than a simple plain text.

What do you think?

### PR DESCRIPTION
**Pull request by privat**
Close #1382

### CODE REVIEW

**Comment by ablondin** [comment]
I took a quick look at all README and it seems ok with me. Thanks for the quick fix!
+1

**Comment by xymus** [comment]
+1

**Comment by BlackMinou** [comment]
+1

**Comment by Morriar** [comment]
+1

**Comment by privat** [comment]
reroll: also fixed a whitespace issue

**Pull request merged**
