### PR TITLE
Warn useless do block

### LINKED ISSUE #1437: Loop unPOLA
So loop blocks are great, they allow the programmer to write the oh-so-infamous infinite loops.

As any infinite loop should go, we should be able to escape them anytime we'd like, via the good old `break` statement.

And oh was I surprised when I got this:

~~~nit
loop do
    break
end
print "x"
~~~

This yields an error at compile-time: `Error: unreachable statement. print "x"`

You got it, the `do end` is a simple block and the break escapes the block, not the loop, and the rest is history !

In all seriousness, maybe a warning should be raised when doing a `loop do` or the construction should be parsed as a loop block, not as a loop encompassing a block.

NOTE: Should it be tagged as `Bug` or as `It's not a bug, it's a feature` ?

### PR DESCRIPTION
**Pull request by privat**
Warn useless do block, like

~~~nit
loop do 
  print 1
end
~~~

Close #1437

### CODE REVIEW

**Comment by BlackMinou** [comment]
+1

**Comment by R4PaSs** [comment]
:shipit:

**Comment by Morriar** [comment]
@privat what is the good way to writte your example?

**Comment by privat** [comment]
@Morriar: remove the `do`

~~~nit
loop 
  print 1
end
~~~

**Pull request merged**
