### PR TITLE
c_tool: reorder CC arguments since the semantic between gcc and clang differs

### PR DESCRIPTION
**Pull request by privat**
Just a reordering to really silent the warning on osx

### CODE REVIEW

**Comment by R4PaSs** [comment]
:shipit:

**Comment by privat** [comment]
Note: this PR is the first one that makes OSX go green on the tests.
It was the objective of the whole serie. http://gresil.org/jenkins/job/CI%20Github%20OSX/

**Comment by Morriar** [comment]
+1

**Comment by Morriar** [comment]
I too, like when Nit goes green.

**Pull request merged**
