### PR TITLE
NSieve optimization

### PR DESCRIPTION
**Pull request by R4PaSs**
The `shootout_nsieve` benchmark has been present in tests for a long time (longer than I can remember actually).

Up until now, its performances have been constant and quite good, since the work was done in less than 15ms.

However, due to its use of `FlatBuffer` and indexed access, it degenerates when using UTF-8 (see #1277) and the run time of `shootout_nsieve` scales from `0m0.011s` to `1m59.870s`.

This PR fixes that.

### CODE REVIEW

**Comment by R4PaSs** [comment]
As requested by @privat, added variant using `Bytes` from standard library

**Comment by privat** [comment]
what is the time for each version after the PR?

**Comment by R4PaSs** [comment]
Times are very similar, with nitg-g they both amount to `0m0.006s`, using nitg-s, they both give a runtime of `0m0.016s`-`0m0.018s`

Though the run times are too short, I'll try with a higher value of N to see if there's really a difference

**Comment by R4PaSs** [comment]
With N = 10:

~~~shell
$- nitc tests/shootout_nsieve_bytes_alt.nit
$- time ./shootout_nsieve_bytes_alt
Primes up to 10240000 679461
Primes up to 5120000 356244
Primes up to 2560000 187134

real	0m2.865s
user	0m2.856s
sys	0m0.004s

$- nitc --global tests/shootout_nsieve_bytes_alt.nit
$- time ./shootout_nsieve_bytes_alt
Primes up to 10240000 679461
Primes up to 5120000 356244
Primes up to 2560000 187134

real	0m0.442s
user	0m0.441s
sys	0m0.000s
~~~

~~~shell
$- nitc tests/shootout_nsieve.nit
$- time ./shootout_nsieve
Primes up to 10240000 679461
Primes up to 5120000 356244
Primes up to 2560000 187134

real	0m3.746s
user	0m3.738s
sys	0m0.008s

$- nitc --global tests/shootout_nsieve.nit
$- time ./shootout_nsieve
Primes up to 10240000 679461
Primes up to 5120000 356244
Primes up to 2560000 187134

real	0m0.436s
user	0m0.436s
sys	0m0.000s

~~~

**Comment by privat** [comment]
Nice. I'm however surprised that the Bytes implementation (shootout_nsieve_bytes_alt) is faster that the CByteArray one (shootout_nsieve) because of unboxing

**Comment by privat** [comment]
+1

**Comment by privat** [comment]
Hum, I just looked at `lib/c.nit` and in fact the boxing issue is also present in it. So most services should be as inefficient to call as with the pure Nit implementation  (Bytes), except that there is also a FFI overcost in `c.nit`. That could explain why the native implem is faster for the nsieve bench.

**Pull request merged**
