### PR TITLE
Add missing nodes in the AST

### PR DESCRIPTION
**Pull request by privat**
Originally, the AST was very abstract and included only node that useful semantically, thus dropped most keywords and symbols during the AST transformation done by sablecc.

After all these years, I was a very bad idea that cause useless complexity for preople that wanted to program precise error messages or develop tools like nitlight or nitpretty.

So, this PR add back most of these nodes in the AST. Future PR may simplify the code of the tools to deal we a more complete AST thus remove heuristics to retrieve the missing tokens.

### CODE REVIEW

**Comment by MehdiAit** [comment]
dose the PR fixe the nullable node ?

**Comment by privat** [comment]
@MehdiAit what are you talking about? Do you have a issue number?

**Comment by MehdiAit** [comment]
For example I have n_node as production and i want to check if this node is null or not. I can't do 
"if n_node != null". I must create a variable : var node = n_node after this I can check if the node is null or not ( I don't know if this PR have a link with this case. I've seen "missing nodes" on the PR title's)

**Comment by Morriar** [comment]
@MehdiAit No.

This PR introduces some token that was not saved in the AST.

Before that, when you visited the AST for a `do .. end` block for instance, the `end` token was not saved in the AST.

For basic compilation it's ok but when you think about pretty printing code for example, you had no way to know exactly where the `end` token was in the original code and had to guess it's location using another way (like checking the location of the last statement in the block).

**Comment by Morriar** [comment]
+1 this will be very useful.

Is it possible to add something to locate comments? In nitpretty, dealing with non-MDoc comments and showing them at the right place is a PITA...

**Comment by R4PaSs** [comment]
:shipit:

**Comment by privat** [comment]
@MehdiAit because sablecc always inline `?` thus causing the lr automaton to be larger. As a rule of thumb, I try to avoid ? and * unless they are needed to solve conflicts.

**Comment by privat** [comment]
@Morriar since comment could appear basically anywhere, I think it is easier to deal with them using `next_token` and `prev_token`, unless you have a more precise request.

**Comment by MehdiAit** [comment]
:shipit:

**Pull request merged**
