### PR TITLE
lib/array: remove useless cast to comparable.

### PR DESCRIPTION
**Pull request by Morriar**
Signed-off-by: Alexandre Terrasa <alexandre@moz-code.org>

### CODE REVIEW

**Comment by R4PaSs** [comment]
That's an easy-to-read PR !

:shipit:

**Comment by Morriar** [comment]
Hum... all tests are failing. Adaptative typing error?

**Comment by privat** [comment]
Fixed adaptive typing error! The bug is fixed and the cast is now useless but c_src still need it because old compilers are grumpy and like that things are done in the old way even when it is ridiculous and inefficient for nowadays standards.

**Comment by privat** [comment]
marked stalled, to reapply when c_src is updated

**Pull request merged**
