### PR TITLE
Advice on useless repeated types

### PR DESCRIPTION
**Pull request by Morriar**
With this PR, nitpick and other tools are able to suggest to remove useless types in signature redefinition with the option `-W`.

Example:

~~~nit
class A
	fun foo(a: Bool) do end
end

class B
	super A

	redef fun foo(a: Bool) do end
end
~~~

~~~
$ nitc test.nit -W
test.nit:8,19--22: Warning: useless type repetition on parameter `a` for redefined method `foo` (useless-signature)
		redef fun foo(a: Bool) do end
		                 ^
Errors: 0. Warnings: 1.
~~~

### CODE REVIEW

**Comment by R4PaSs** [comment]
Nice ! I can't help but think that this was done to grind some nitcoins :)

But that's cool, :shipit: !

**Comment by privat** [comment]
~~~
+ unitrun.sh run-check-whitespaces git log --oneline --check FETCH_HEAD..HEAD
e576208 lib/misc: remove useless types
d41a68b lib/json: remove useless types
7599b41 lib/nitcorn: remove useless types
d653e94 lib/socket: remove useless types
221bb47 lib/trees: remove useless types
4939b15 lib/template: remove useless types
d5e7e52 lib/string_experimentations: remove useless types
11c29b8 lib/mnit: remove useless types
2bddeab lib/curl: remove useless types
009f280 lib/sqlite: remove useless types
fda76d7 lib/geometry: remove useless types
69aaa58 lib/neo4j: remove useless types
c896e48 lib/sax: remove useless types
b964c74 lib/android: remove useless types
2282d90 lib/standard: remove useless repeated types in `standard`
c3b1af1 tests: test advice for useless repeated type in redef
0ce78ff model: check useless repeated types in signatures
7f274ff nitpick: fix a typo in comments
+ unitrun.sh run-check-signed_off_by checksignedoffby.sh FETCH_HEAD HEAD
2282d90 lib/standard: remove useless repeated types in `standard`
Missing Signed-off-by: Alexandre Terrasa <alexandre@moz-code.org>
c3b1af1 tests: test advice for useless repeated type in redef
Missing Signed-off-by: Alexandre Terrasa <alexandre@moz-code.org>
+ Command returned 1
+ unitrun.sh run-check-license /home/privat_j/bin/checklicense.sh FETCH_HEAD HEAD
tests/test_advice_repeated_types.nit
~~~

**Comment by BlackMinou** [comment]
+1 when build doesnt fail :)

**Comment by Morriar** [comment]
Reroll with licences and signed-offs.

**Comment by privat** [comment]
+1 even if I do not understand why the warning was not added in `check_signature` need the associated error

**Comment by Morriar** [comment]
@privat I understand your suggestion.

**Comment by Morriar** [comment]
Reroll passing more tests.

**Comment by privat** [comment]
Please solve the merge conclicts

**Comment by Morriar** [comment]
Reroll for merge conflicts

**Pull request merged**
