### PR TITLE
Remove the interpreter, it is too slow.

### PR DESCRIPTION
**Pull request by privat**
Our main goal is performance.
And since FFI did not work with it, it was basically useless anyway.

### CODE REVIEW

**Comment by jpages** [comment]
+1 but only if we remove the virtual machine too !

**Comment by Morriar** [comment]
#AprilFools'Day?

**Comment by R4PaSs** [comment]
:shipit:, the interpreter has no interest.
Let the debugger die.

And I agree with @jpages, we should get rid of the VM at the same time.

**Comment by jpcaissy** [comment]
LGTM

**Comment by privat** [comment]
On a assez rit. À l'année prochaine.

**Pull request closed without merging**
