### PR TITLE
beta version of new opportunity

### PR DESCRIPTION
**Pull request by amineorion**
Here is the first version of new opportunity, please review the code in general ( there is other changes need to be done ) and see UI and give me your remarks, thanks

### CODE REVIEW

**Comment by xymus** [comment]
Is it deployed on a server somewhere public?

I've tried it locally, it looks really promising even if there's not much to see yet.

What is the plan with the main "Meetups" page? We previously avoided listing all meetups, it's a simple way to control who is invited to each event and to prevent spam.

Do you really need all 396 files? We previoulsy used a CDN to get the Bootstrap files, or you can automate the download and extraction of the Angular files from the Makefile. You can do something similar to this Makefile rule to download a file (`libs/cardboard.jar`) only when it does not exist locally: https://github.com/xymus/nit/blob/gamnit/lib/gammit/examples/mineit/Makefile#L51

I also got a compilation error (it was easy to fix):
~~~
src/opportunity_web.nit:16,8--17: Error: module name missmatch; declared config_web file named opportunity_web
~~~

**Comment by xymus** [comment]
You can remove the fields "Date" and "Place" from the meetup creation page and replace them with a single description field. It is illogical to ask for a precise date when the polling to find the date of an event.

Bonus points if the description field accepts text with markdown formatting! It can then be converted to HTML using the markdown lib: https://github.com/privat/nit/tree/master/lib/markdown

**Comment by amineorion** [comment]
I just worked on the general architecture ( in code ).I used bower, but i forget to make git don't track libs files. My problem is there i don't think i understand the app 100%, but if the objective is really, someone create a meetup, so i think we need address, and date, if users want to search a meetup by place and date, it is the best way to do it.

**Comment by privat** [comment]
jenkins: ok to test

**Comment by R4PaSs** [comment]
I agree with @xymus, could you create a script or use a CDN for all the lib JS files ? It make the diff way too big to read from a browser, and it's kinda hard to comment modifications because of this :)

Any chance you could upload a demo version for us to try too ?

Thanks !

**Comment by amineorion** [comment]
I m having problems to make it run behind nginx server, any ideas ( PS: i m using same config as it is a nodejs app)

**Comment by Morriar** [comment]
Can you give us any details about those problems?

**Comment by amineorion** [comment]
here is the config I used: https://gist.github.com/amineorion/b4429bfa1ef3fd0a4c60, the problem as you can see here http://54.68.169.103/ , it is empty, I tried it in localhost, it works perfectly, i got no errors from the server.

**Comment by amineorion** [comment]
at a second look at the log file, I got HTTP Error 405 Method not allowed

**Comment by Morriar** [comment]
Hum, I see,

Nginx doesn't seem to like post on (presumed) static content. Maybe this
can help you:
http://leandroardissone.com/post/19690882654/nginx-405-not-allowed

Alexandre

2015-03-03 18:22 GMT+01:00 amine <notifications@github.com>:

**Comment by amineorion** [comment]
Ok i just deleted some extra params and it works, thanks.

**Comment by amineorion** [comment]
Ok here is a live test version ( everything is still super limited, i will do some update soon as i m sure ppl are ok for the code ) http://54.68.169.103/

**Comment by Morriar** [comment]
### On the PR

Well... You will have some difficulties finding reviewers for that PR. The reason? It's too big. I give you a hint: if your browser crashes when you click on the "Files changed" tab, you are doing it wrong.

First of all, you should organize and explain your changes in commits. Commits help us to understand what you are changing and why. Each commit should have a unique concern, the commit list can then be read as a `Change log`.

When you have clean commits, makes many little PR instead of only one big PR. It makes the work of reviewers easier. Doing so, we can grasp the essence of the changes instead of trying toi understand what the heck you are doing with all that 396 files.

An example with your code:
* Make one PR to present the changes in the core (what you changed in the already existing files). So @xymus  and @R4PaSs will be able to check what you are editing in their code.
* Make one PR to introduce the new design.

Both these steps can be cut down in many small PRs if needed. Furthermore, the diff will be more readable once you have removed all those files that can be loaded from CDN.

### On the prototype

I'm not sure, I understand what you are doing in here. Actually, I'm not sure *you* understand what you are doing here.

Opportunity is designed to be an open-source clone of http://doodle.com/fr/. I suggest you to try it and see the expected behavior.
* The one and only goal of that app is to find a date for a meetup so why do you ask for the meetup date in the meetup creation? Like in Doodle (and previous version of Opportunity), you should let the user select a list of possible dates and participants will choose between them.
* Meetups should not be listed in any pages since they are "kind of private". To share a meetup with someone, you are expected to share the URL of the meetup.

Also, I don't understand why we are losing features here? Opportunity was working (nearly) fine before, why removing working features?

**Positive remark: The UI looks fine though...**

### On the code

Please rewrite your PR if you want some code review...

**Comment by privat** [comment]
Premièrement, merci pour la PR, que j'interprète comme une proposition de pistes d'amélioration.

Déjà, avoir un proto en ligne permet mieux de montrer au monde les améliorations coté client. Grâce à ça, les gens semblent d'accord que le rendu fait plus professionnel.

En ce qui concerne les fonctionnalités, la liste de #811 compte pas mal de points, mais bien évidemment en premier il faut comprendre l'objectif du logiciel (ce que le README n'explique pas vraiment en fait, un point à rajouter dans la TODO :) ). Opportunitiy est un [doodle-like][http://en.wikipedia.org/wiki/Doodle.com] qui permet aux gens de planifier des événements en petit groupe et de façon relativement privée : il faut avoir reçu un lien précis, généralement envoyé par le créateur du sondage, pour pouvoir émettre son opinion.

Il semble que tu ais ajouté un page de garde qui liste publiquement les sondages ouverts ce qui va assez à l'encontre du principe de base du logiciel, c'est pourquoi les gens qui ont commenté précédemment doutent de la pertinence de la fonctionnalité. Toutefois, j'y vois une idée pour lister les sondages dont on est l'administrateur ou auxquels on a participé, cela veut-dire avoir un mode (optionnel) authentifié ou quelque chose du genre.

Pour le reste du proto, j'ai pas réussi à jouer plus avec l'outil car les butons *boite* et 
*crayon* (y avait pas de légende ou de titre) ne faisaient rien.

En ce qui concerne le code, la plus grosse difficulté des nouveaux venus est de s'adapter au [workflow de Nit][http://nitlanguage.org/internal/workflow/], principalement à la relecture de code, ce qui veut dire que toute contribution, en plus de fonctionner et d'être efficace doit être relue et validée. En pratique cela veut dire qu'une contribution doit être compréhensible (je peux comprendre ce que tu fais), expliquée (tu me donne l’information suffisante pour comprendre ce que tu fais) et justifiée (tu as raison de faire ce que tu fais).

Une autre difficulté importante est la cohésion des PR (feature-branch) ce qui veut dire que chaque PR doit se concentrer sur une seule préoccupation (par exemple une PR par entrée de la TODO-liste).
C'est assez difficile pour qui n'est pas habitué car il est habituel de bricoler son code en continue et anarchiquement dans son répertoire de travail, mais bosser en feature-brach est actuellement l'approche utilisée par la plupart des gros projets libre et plusieurs des méthodes agiles il me semble, car elle permet le passage à l'échelle et maintient un bon niveau de qualité car une feature-branch peut-être maintenue en développement sans bloquer les feature-branches indépendantes (du même développeur ou d'un autre, sur un même sous-système ou un autre) qui peuvent être intégrées au tronc principal (master).
En général, plusieurs petites PR sont intégrées plus rapidement que quelques grosses (même si le code au final est le même) car elles sont relues plus rapidement.

En ce qui concerne l'évolution et la maintenance.
Il y a deux principes en développement efficace que l'on essaye d'appliquer dans le projet: 
[[la refactorisation en continue|http://refactoring.com/catalog/]] et la stabilité [[http://en.wiktionary.org/wiki/if_it_ain%27t_broke,_don%27t_fix_it]].
Cela semble contradictoire, mais ce que j'aime bien dire aux étudiants c'est que les modifications du code doivent être le plus possible strictement monotone au niveau de la qualité : j'ai rien contre du code de mauvaise qualité, c'est en général mieux que rien ; par contre je n'aime pas quand ce code de mauvais qualité remplace du bon code (évidemment) ou s'il remplace du code d'équivalente mauvaise qualité (car il n'y a pas de progrès et je préfère du mauvais code qu'on connaît à du mauvais code qu'on connaît pas encore).

C'est à la charge du contributeur du code de justifier l'augmentation de la qualité (par l'ajout de fonctionnalité ou l'amélioration d'exigences non fonctionnelles par exemple).
C'est d'autant plus vrai si le code a été principalement développé par quelqu'un d'autre, non pas pour des raison d'ego (quoi que nous sommes humains) mais parce que les développeurs précédent ont peut-être un vision ou une compréhension différence du domaine ou du logiciel : il faut donc justifier les changements pour éviter les malentendus et faire clairement ressortir les améliorations proposées.

Dans la PR présentée ici, il ya beaucoup de changement de code difficile à relire, car les modifications sont relativement entremêlée (pas de séparation en feature branches), dont la justification n'est pas donnée (aide ton relecteur) et donc la nature de plusieurs des changements n'est même pas claire (réécriture complète, refactorisation de code, ou simple déplacement?)

Pour la suite, je te propose d'isoler les propositions indépendantes en des PR distinctes (avec des commits autonomes): plutôt que de te battre avec les outils git, le plus simple et souvent de repartir d'une branche propre et de récrire (ou copier-coller) les modifications.
En particulier, fait une PR pour l'utilisation de angular (an touchant au moins possible au code Nit), et une PR pour chacune des entrées de la TODO liste (ou par groupe de refactorisations cohérentes).

Pour s'habituer au worflow de Nit, au logiciel opportunity et aux outils git, je te conseille aussi de commencer par les entrées de la TODO qui sont faciles (voire triviales). Ainsi, cela t'évitera de luter à la fois sur le terrain du code et du workflow.

En terme de pratique de travail, chacun a sa méthode, plusieurs gardent leur approche anarchique et maintiennent leur version du dépôt (non publiée) de laquelle ils extraient de temps en temps des PR : en copiant collant du code pour faire de nouveaux commits.
Moi j'utilise une approche hybride dans laquelle je crée une branche propre pour une nouvelle fonctionnalité et développe anarchiquement mais en créant des commits sémantique (parfois partiels) au fur et à mesure du développement, ensuite quand j'obtiens ce que je veux je réécrit l'histoire des commits pour avoir quelque chose de lisible et cohérent avec un début, un milieu et une fin. Si j'ai eu du nez lors de la création des commits partiels, un simple rebasement interactif avec squashage fait l'affaire, autrement quand j'ai pas de chance, j'agrège l'ensemble des commits en un seul diff que je redécoupe en une nouvelle série autonome et élégante de commits.

**Comment by privat** [comment]
@amineorion  ping?

**Comment by privat** [comment]
lack of activity :(

**Pull request closed without merging**
