### PR TITLE
modelize: ask that attributes in refinements are either noautoninit or have a value

### PR DESCRIPTION
**Pull request by privat**
Without value, attributes in introductions does not have the same semantic that attributes in refinements

In introduction attributes are implicitly `autoinit`, in refinements they are `noautoinit`.

This is not POLA since

* this confuse beginners
* readers have to remember if they are in an intro or a refinement
* aditionnal cognitive fragility in constructors (more cases and rules to take in account)

This PR make `autoinit` the default and ask that attributes declared in refinement are either annotated `noautoinit` or have a default value.
This way, the writer has to think about the implication of adding a new attributes in existing classes, especially to think about their initialization. Thus this could help the programmer to avoid bad error.

For the moment, I just display a warning because I want to wait for feedback before doing a big migration (or doing nothing if people hate that), I also want to use jenkins to count and locate these new warnings.

Related to #1322

### CODE REVIEW

**Comment by privat** [comment]
results: *only* 161 cases... not that much

http://gresil.org/jenkins/job/CI_github/2784/warnings2Result/type.1671528471/

**Comment by xymus** [comment]
This may raise many warnings in my code. I got used to rely on refinements to add cache and other non-vital attributes. Still, it may be interesting to encourage to use a default value. +1

Just a thought, if we were to support adding optional and named parameters to signatures on specialization and refinements (as discussed in #1281), we could also accept `nullable` attributes in refinements as `autoinit`. When instantiating the class, we could set the optional attribute in the constructor call without breaking the signature of the original constructor.

**Comment by privat** [comment]
reroll: use `advice` instead of `warning` to be more silent and pass tests

**Comment by Morriar** [comment]
+1

**Pull request merged**
