### PR TITLE
Remove niti hacks on NativeString and NativeFile

### PR DESCRIPTION
**Pull request by xymus**
Previously, the interpreter used a FlatBuffer to implement NativeString and a File to implement NativeFile. This caused issues with applications using (mostly) `is_address_null` which could not be implemented correctly with these implementations.

This PR uses a real NativeString and NativeFile to implement the same class. For NativeFile, it is handled by the FFI so removing the old code is enough. For NativeString, many of its methods are intern so they had to be updated.

### CODE REVIEW

**Comment by Morriar** [comment]
+1

**Comment by privat** [comment]
+1

**Comment by privat** [comment]
You broke the interpreter bootstrap because the parser still use the legacy ffi and you just disabled it

~~~
$ ../bin/nit -v -- nit.nit ../tests/base_simple3.nit -v -v
parser/tables.nit:20,2--22,54: Runtime error: NOT YET IMPLEMENTED extern tables#TablesCapable#lexer_goto
~~~

http://gresil.org/jenkins/job/nit_bootstrap/873/console

**Comment by xymus** [comment]
I removed the problematic commit.

**Pull request merged**
