### PR TITLE
Rename Container to Ref

### PR DESCRIPTION
**Pull request by xymus**
The `Container` class is widely misunderstood and underused.  However it can be very useful to implement a return parameter. This PR rename the class according to this usage. It will make some signatures easier to understand: (example inspired by a similar function from `UDPSocket`)

~~~nit
# This method has 3 outputs:
# * The received message written into `buffer`.
# * The number of bytes written as the return value.
# * The information on the sender of the message is stored in `sender_info`.
fun recv_from(buffer: NativeString, sender_info: Ref[nullable SocketAddress]): Int
~~~

### Bonus Ref tip!

`Ref` can also be used as a hackish equivalent to a `static` variable in C. This example use the dreaded `once` keyword to easily get a singleton, but it could be done cleaner with an attribute in `Sys`.

~~~nit
fun foo
   ...

    # Count the number of times foo is executed
    var counter = once new Ref[Int](0)
    counter.item += 1
    print "foo has been executed {counter.item} times"
end
~~~

### CODE REVIEW

**Comment by R4PaSs** [comment]
I'm baffled by such a change, :shipit: !

**Comment by xymus** [comment]
@R4PaSs, I know, it will take a while to get used to the new name!

**Comment by Morriar** [comment]
+1

> RIP Container.

**Comment by privat** [comment]
+1. Changed your example to use a `fun` instead of a `var`.

**Pull request merged**
