### PR TITLE
Fix nitunit for `String::format`

### PR DESCRIPTION
**Pull request by Morriar**
Since the code block was badly indented, it was not tested by `nitunit`.

Once the indentation was corrected, `nitunit` found that the test was failing.

Signed-off-by: Alexandre Terrasa <alexandre@moz-code.org>

### CODE REVIEW

**Comment by Morriar** [comment]
@R4PaSs you may want to check this one ;)

**Comment by R4PaSs** [comment]
Yup, I guess using tabs instead of 5 spaces is not a Nitunit :/

Any chance there's a README somewhere to explain what kind of spacing to use and where ?

And good job for the whitespaces, I guess they were there before the whitespace checks :whistle:

**Comment by R4PaSs** [comment]
Oh, :shipit: !

**Comment by privat** [comment]
+1

**Comment by Morriar** [comment]
****ing neo transiant test failure.

One day, I will fix that. One day.

**Pull request merged**
