### PR TITLE
Fix light FFI in interpreter on OS X

### LINKED ISSUE #1623: Bug on MacOS when launching the interpreter
Hi, all!

On MacOS, there seems to be a problem when launching the Nit interpreter (tested at commit 06cef8ab529c01ce18a5c14fd9a94b76db18b87b):

~~~
 [graphs] blondin [~/Applications/nit]
 $ git co 06cef8ab529c01ce18a5c14fd9a94b76db18b87b
 $ make
cd src; make
***************************************************************
* Compile binaries from NIT source files                      *
***************************************************************
./git-gen-version.sh
Version v0.7.7-94-g06cef8a
test -d ../bin || mkdir ../bin
./nitc_0 --semi-global -v --dir ../bin nitc.nit nitpick.nit nit.nit nitdoc.nit nitls.nit nitunit.nit nitpretty.nit nitmetrics.nit nitx.nit nitlight.nit nitdbg_client.nit nitserial.nit
*** PARSE ***
*** SEMANTIC ANALYSIS ***
*** PROCESS nitc ***
*** GENERATING C ***
*** WRITING C ***
*** COMPILING C ***
*** PROCESS nitpick ***
*** GENERATING C ***
*** WRITING C ***
*** COMPILING C ***
*** PROCESS nit ***
*** GENERATING C ***
*** WRITING C ***
*** COMPILING C ***
*** PROCESS nitdoc ***
*** GENERATING C ***
*** WRITING C ***
*** COMPILING C ***
*** PROCESS nitls ***
*** GENERATING C ***
*** WRITING C ***
*** COMPILING C ***
*** PROCESS nitunit ***
*** GENERATING C ***
*** WRITING C ***
*** COMPILING C ***
*** PROCESS nitpretty ***
*** GENERATING C ***
*** WRITING C ***
*** COMPILING C ***
*** PROCESS nitmetrics ***
*** GENERATING C ***
*** WRITING C ***
*** COMPILING C ***
*** PROCESS nitx ***
*** GENERATING C ***
*** WRITING C ***
*** COMPILING C ***
*** PROCESS nitlight ***
*** GENERATING C ***
*** WRITING C ***
*** COMPILING C ***
*** PROCESS nitdbg_client ***
*** GENERATING C ***
*** WRITING C ***
*** COMPILING C ***
*** PROCESS nitserial ***
*** GENERATING C ***
*** WRITING C ***
*** COMPILING C ***

 $ cat test.nit 
print "hello"

 $ nit test.nit 
ld: unknown option: -soname
clang: error: linker command failed with exit code 1 (use -v to see invocation)
/Users/blondin/Applications/nit/lib/standard/math.nit:462,1--465,34: Runtime error: FFI Error: Failed to link native code using `gcc -Wall -shared -Wl,-soname,math.so -g -o nit_compile/standard__math.so nit_compile/standard__math._nitni.o nit_compile/standard__math._ffi.o -lm`
	# Reinitialize the pseudo-random generator used by the method `rand` and other.
	^
,---- Stack trace -- - -  -
| math#Sys#srand (/Users/blondin/Applications/nit/lib/standard/math.nit:462,1--465,34)
| math#Sys#init (/Users/blondin/Applications/nit/lib/standard/math.nit:435,3--7)
| environ#Sys#init (/Users/blondin/Applications/nit/lib/standard/environ.nit:65,2--69,4)
`------------------- - -  -
~~~

However, when I compile the file, everything works fine:

~~~
 [graphs] blondin [~/Applications/nit/lib/graphs]
 $ nitc test.nit 

 [graphs] blondin [~/Applications/nit/lib/graphs]
 $ ./test
hello
~~~

Any idea what happens?

Thanks.

### PR DESCRIPTION
**Pull request by xymus**
Fix #1623 by removing the soname declaration (the soname was more of a placeholder at this time anyway). Also take this opportunity to remove the `-g` flag.

The fixes to the md5 modules update it to the latest style and use the nity/native pattern to avoid callbacks so it is light FFI compatible. This was used to test the interpreter on OS X.

### CODE REVIEW

**Comment by privat** [comment]
+1

**Comment by privat** [comment]
Add a commit that drops the line `ld: unknown option: -soname` from the file `tests/sav/Darwin/todo`

**Comment by R4PaSs** [comment]
:shipit:

**Comment by privat** [comment]
You laughed when I suggested you to run nitunit on md5 on your machine. Who is launching now?

**Comment by privat** [comment]
Anyway, the interpreter seems to work on osx again: http://gresil.org/jenkins/job/CI%20Github%20OSX/66/testReport/tests.nitcs.src/nit/

**Comment by xymus** [comment]
Yeah, my quick repetitions on vim ate one character too many... I should be fixed now.

**Pull request merged**
