### PR TITLE
Standardize the name of Android API level annotations 

### PR DESCRIPTION
**Pull request by xymus**
Rename `min_api_version`, `max_api_version` and `target_api_version` to `android_api_min`, `android_api_max` and `android_api_target`. It fits better with the other `android_` annotations (as seen in `lib/android/aware.nit`) and with the `app_` annotations.

> Please ignore the first commit, it is from #1325.

### CODE REVIEW

**Comment by privat** [comment]
+1

**Comment by BlackMinou** [comment]
+1

**Comment by MehdiAit** [comment]
+1

**Comment by privat** [comment]
@xymus can you solve merge conflicts? I prefer that you hold the knife yourself.

**Pull request merged**
