### PR TITLE
Fix FFI with private extern classes not needing a "C Header" block

### PR DESCRIPTION
**Pull request by xymus**
According to the [manual of the C FFI for wrappers](http://nitlanguage.org/FFI/wrapping_C_libraries/), a private extern class does not need to import (or declare) its C equivalent type in the "C header" it can be done only in the "C body" (or the default "C" block).

This bug broke this feature. It may have been reintroduced by 16f94e0, or maybe even before. This PR adds a test to prevent future regression.

Bug referenced in #1520.

### CODE REVIEW

**Comment by privat** [comment]
+1

**Comment by BlackMinou** [comment]
+1

**Comment by privat** [comment]
in fact, on of the issue on the sav with niti-ffi reported in https://github.com/privat/nit/pull/1520#issuecomment-113098703 was caused by this PR

I do not know if it is something that should be solved or marked UNDEFINED so just rebase and do what you prefer

http://gresil.org/jenkins/job/nit_tests/engine=niti/904/testReport/

**Comment by xymus** [comment]
Yeah, it's the GCC warning. It passes the tests with nitc since it is raise at compilation but it fails in niti since compilation happens at runtime.

**Pull request merged**
